# Generated by Django 4.2.5 on 2023-10-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_responses_promt'),
        ('doc_processing', '0003_files_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.chatrooms'),
        ),
    ]
