# Generated by Django 4.2.5 on 2023-10-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0002_remove_responses_promt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
